version: 2

project_name: cloudrun-local

before:
  hooks:
    - go mod tidy

builds:
  - id: cloudrun-local
    main: ./cmd/cloudrun-local
    binary: cloudrun-local
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: cloudrun-local
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: ngalaiko
    name: cloudrun-local
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## cloudrun-local {{ .Tag }}

    Run Google Cloud Run services and jobs locally with proper service account impersonation.
  footer: |
    ## Installation

    ### Go Install
    ```bash
    go install github.com/ngalaiko/cloudrun-local/cmd/cloudrun-local@{{ .Tag }}
    ```

    ### Binary Download
    Download the appropriate binary for your platform from the assets below.

    ---

    **Full Changelog**: https://github.com/ngalaiko/cloudrun-local/compare/{{ .PreviousTag }}...{{ .Tag }}
